companieshouse/chd-order-api

pom.xml, src/main/java/uk/gov/companieshouse/chd/order/api/controller/HealthcheckController.java, src/main/resources/application.properties, src/main/resources/application.yaml, src/test/java/uk/gov/companieshouse/chd/order/api/controller/HealthcheckControllerIntegrationTest.java, src/test/resources/application.properties
Amendments made to get the unit tests running
=> Amendments made to get the unit tests running

pom.xml, src/main/java/uk/gov/companieshouse/chd/order/api/config/ApplicationConfig.java, src/main/java/uk/gov/companieshouse/chd/order/api/controller/HealthcheckController.java, src/main/java/uk/gov/companieshouse/chd/order/api/interceptor/ApiKeyAuthenticationInterceptor.java, src/main/java/uk/gov/companieshouse/chd/order/api/interceptor/ApiKeyAuthorisationInterceptor.java, src/test/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesControllerTest.java, src/test/java/uk/gov/companieshouse/chd/order/api/interceptor/ApiKeyAuthenticationInterceptorTest.java, src/test/java/uk/gov/companieshouse/chd/order/api/interceptor/ApiKeyAuthorisationInterceptorTest.java, src/test/java/uk/gov/companieshouse/chd/order/api/util/TestConstants.java
added auth with api key
resolves: GCI-1450
=> added auth with api key

src/main/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesController.java, src/main/java/uk/gov/companieshouse/chd/order/api/dto/MissingImageDeliveriesDTO.java, src/test/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesControllerIntegrationTest.java, src/test/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesControllerTest.java, src/test/postman/CHD_Order_API.postman_collection.json
Sonar report: http://code-analysis.platform.aws.chdev.org:9000/dashboard?id=uk.gov.companieshouse%3Achd-order-api&pullRequest=6.
=> GCI-1614: Add filing history type to DTO

src/main/java/uk/gov/companieshouse/chd/order/api/controller/ApiError.java, src/main/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesController.java, src/main/java/uk/gov/companieshouse/chd/order/api/dto/MissingImageDeliveriesDTO.java, src/main/java/uk/gov/companieshouse/chd/order/api/logging/LoggingUtils.java, src/main/java/uk/gov/companieshouse/chd/order/api/validator/CreateItemRequestValidator.java, src/test/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesControllerTest.java, src/test/java/uk/gov/companieshouse/chd/order/api/testUtils/ItemSetup.java, src/test/java/uk/gov/companieshouse/chd/order/api/validator/CreateItemRequestValidatorTest.java
Validates the creation of the mid item and outputs message errors for missing or null fields.
=> Gci 1449 implement request validation

src/main/java/uk/gov/companieshouse/chd/order/api/model/OrderHeader.java, src/main/java/uk/gov/companieshouse/chd/order/api/service/OrderService.java, src/test/java/uk/gov/companieshouse/chd/order/api/service/OrderServiceIntegrationTest.java
Adds `ORDERVALUE` column to `OrderHeader`
=> Gci 1451 create chprd records add order value

src/main/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesController.java, src/main/java/uk/gov/companieshouse/chd/order/api/exception/OrderServiceException.java, src/main/java/uk/gov/companieshouse/chd/order/api/model/OrderDetails.java, src/main/java/uk/gov/companieshouse/chd/order/api/service/OrderService.java, src/test/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesControllerTest.java, src/test/java/uk/gov/companieshouse/chd/order/api/service/OrderServiceTest.java
If the insertion inside db fails then the service should produce a 500 Internal Server Error!
=> Gci 1618 deal with db internal server error

src/main/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesController.java, src/main/java/uk/gov/companieshouse/chd/order/api/exception/DuplicateEntryException.java, src/main/java/uk/gov/companieshouse/chd/order/api/exception/OrderServiceException.java, src/main/java/uk/gov/companieshouse/chd/order/api/service/OrderService.java, src/test/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesControllerTest.java, src/test/java/uk/gov/companieshouse/chd/order/api/service/OrderServiceTest.java
=> Fix merging

pom.xml
=> Dockerise application

src/main/resources/application.properties
Amended properties to prevent hibernate logs from being included in application logging
=> Bug fix to remove hibernate logging

src/main/java/uk/gov/companieshouse/chd/order/api/model/Customer.java, src/main/java/uk/gov/companieshouse/chd/order/api/service/OrderService.java, src/test/java/uk/gov/companieshouse/chd/order/api/service/OrderServiceTest.java
Amendments to store up to the first 40 characters of the email address in premises and addrline1
Amended Customer to include premises and addrline1 fields
Amended OrderService to check for null email strings and substring if longer than 40 chars
Added unit test for the email address being longer than 40 characters
Added JUnit 5 DisplayName for tests
Jira Ticket : GCI-1743
=> Store email address in premises and addrline1

src/main/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesController.java, src/test/java/uk/gov/companieshouse/chd/order/api/controller/MissingImageDeliveriesControllerTest.java
Convert the filing history type value from RESOLUTIONS to RES
Resolves BI-8179
=> Amendment to convert the filing history type RESOLUTIONS to be RES

pom.xml
DEBT-1428
Amended to use log4j 2.15.0 and structured-logging 1.9.10
=> Amended to use log4j 2.15.0

pom.xml
DEBT-1351
Upgraded structured-logging to 1.9.11 and log4j to 2.17.0
=> Upgraded structured-logging to 1.9.11 and log4j to 2.17.0

pom.xml
DEBT-1351
Updated structured-logging and removed explicit log4j dependencies
=> Updated structured-logging and removed explicit log4j dependencies

suppress.xml
JU-280: Configure suppress.xml for Security warning fix
=> JU-280: Configure suppress.xml for Security warning fix

Makefile, pom.xml, src/main/resources/application.properties, suppress.xml
Tech Debt : Upgrade dependency and dependency vulnerability suppression check
=>  Upgrade dependency and dependency vulnerability suppression check

terraform/groups/ecs-service/main.tf, terraform/groups/ecs-service/variables.tf
Tech debt for chd order api + resollving cpu issue in prod.
ticket : JU-519
=> modified required cpu to resolve prod issue

README.md
JU-776
-updating readme docs to show load balancers and cluster details
=> JU-776-updating readme docs

README.md
JU-776
-modifying lb path in readme
=> JU-776-modifying lb path in readme

terraform/groups/ecs-service/locals.tf, terraform/groups/ecs-service/main.tf
[JU-1790](https://companieshouse.atlassian.net/browse/JU-1790)
platform tech debt changes:
- remove hc path from the listener paths 
- update terraform-modules version
[JU-1790]: https://companieshouse.atlassian.net/browse/JU-1790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> remove hc path from lb paths and update tf-modules
